export const REGISTER_USER = "REGISTER_USER";

export const ADD_TICKET_TO_USER_LIST = "ADD_TICKET_TO_USER_LIST"

export const GET_JOURNEY_LIST_BY_JOURNEY_DATE = "GET_JOURNEY_LIST_BY_JOURNEY_DATE";
export const GET_CURRENT_JOURNEIES = "GET_CURRENT_JOURNEIES";
export const ADD_JOURNEY = "ADD_JOURNEY";